version: "3.8"
services:
  app:
    container_name: ${APP_NAME:-app}
    build: .
    restart: always
    ports:
      - ${APP_PORT:-5000}:5000
    volumes:
      - ./:${WORKING_DIR:-/app/}
    entrypoint: [ "/bin/sh" ]
    env_file:
      - .env
    depends_on:
      - db
    command:
      [
        "run.sh",
        "${PARAM:-01}"
      ]
  db:
    container_name: ${DB_NAME:-postgres}
    image: postgres:${POSTGRES_VERSION:-15-bullseye}
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-default}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
