name: Contributors
on:
  schedule:
    - cron: "0 1 * * *" # At 01:00 on Everyday.
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "manual run"
        required: false
        default: ""
jobs:
  contributors:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Contribute List
        uses: wow-actions/contributors-list@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          round: true
